### ISSUE TITLE
Temp table statement using the incorrect schema name

### ISSUE THREAD

**Issue by meenahoda** [wmfs/supercopy#285]
The generated statement which creates a temporary table here:

https://github.com/wmfs/supercopy/blob/master/lib/generate-script-statements/add-temp-table-statement.js#L6

appears to be using the incorrect schema name when referring to a table from a different blueprint, in a different namespace. 

Looking here: https://github.com/wmfs/supercopy/blob/master/lib/generate-script-statements/add-update-statements.js#L11

It's getting schema name from options and table name from file info.

File info is collated here: https://github.com/wmfs/supercopy/blob/master/lib/collect-file-info.js#L45 and the table name is grabbed from the csv file name.

I discovered this issue when running this state machine:

https://github.com/wmfs/addressbase-premium-blueprint/blob/master/state-machines/synchronize-addressbase-premium-properties.json

The state resource synchronizingTable calls the package pg-telepods, which calls the package supercopy:

https://github.com/wmfs/pg-telepods/blob/master/lib/sync-changes.js

As seen in the above file, the schemaName is grabbed from the target table (wmfs.gazetteer):

https://github.com/wmfs/addressbase-premium-blueprint/blob/master/state-machines/synchronize-addressbase-premium-properties.json#L17

Meaning it tries to create a temp table for "wmfs.addressbase_premium_property_holding" when it should be "ordnance_survery.addressbase_premium_property_holding"

**Comment by jezhiggins** [comment]
The temporary table name is `${action}_${_.snakeCase(schemaName)}_${_.snakeCase(tableName)}`. Tracing through, the schemaName part is picked up properly - 
```
CREATE TEMP TABLE update_ordnance_survey_addressbase_premium_streets_holding ON COMMIT DROP AS SELECT * FROM ordnance_survey.addressbase_premium_streets_holding WITH NO DATA;
CREATE TEMP TABLE update_ordnance_survey_addressbase_premium_property_holding ON COMMIT DROP AS SELECT * FROM ordnance_survey.addressbase_premium_property_holding WITH NO DATA;
CREATE TEMP TABLE delete_wmfs_streets ON COMMIT DROP AS SELECT * FROM wmfs.streets WITH NO DATA;
CREATE TEMP TABLE delete_wmfs_gazetteer ON COMMIT DROP AS SELECT * FROM wmfs.gazetteer WITH NO DATA;
```

Note, though, that postgres temporary tables don't actually have a schema name - they are created in a special schema space of their own. It's actually an error to try and specify a schema name. The main constraint on a temporary table name is that it's unique, which is why ww compose them with the action, schema name, and so on. 

Having looked again at this code, I think it is correct and is working as intended.
